export const FETCH_ATTACHMENT_REQUEST = 'FETCH_ATTACHMENT_REQUEST'
export const FETCH_ATTACHMENT_SUCCESS = 'FETCH_ATTACHMENT_SUCCESS'
export const FETCH_ATTACHMENT_FAILURE = 'FETCH_ATTACHMENT_FAILURE'
